Hide address fields when empty
tastyigniter/ti-ext-cart pull request #29
Opened 2020-11-10 08:46 UTC by ryanmitchell

In response to: https://github.com/tastyigniter/TastyIgniter/issues/564

2020-11-10 22:10 UTC, sampoyigi requested changes

2020-11-10 22:10 UTC, sampoyigi commented on components/checkout/address_fields.blade.php
>      @if (count($customerAddresses))
Move the `class` line into the `@if` block instead 😉

2020-11-11 06:48 UTC, ryanmitchell commented
Yep that would make sense - why did I not notice that??!

2020-11-13 01:35 UTC, sampoyigi approved these changes

2020-11-13 01:35 UTC, merged