Add more flexibility
tastyigniter/ti-ext-cart pull request #35
Opened 2020-12-13 00:55 UTC by BreakSecurity

Add the possibility to show/hide more fields in checkout page.

fix #30 

The layout when you hide everything is not so clean but I never used bootstrap so if you have suggestions on that...

2020-12-13 01:05 UTC, BreakSecurity commented
Also I noticed this repetition:
![immagine](https://user-images.githubusercontent.com/38836022/102000429-96cc1080-3ce7-11eb-8cd4-8aa641507859.png)
of "checkout terms" is it an error?

2020-12-13 21:09 UTC, sampoyigi commented
Love this PR! Appreciate the effort (especially the docs part)!

The only thing you missed is the validation rules (see Checkout::createRules()). You can prepend the customisable fields with the `sometimes` rules..

> The layout when you hide everything is not the best but I never used bootstrap so if you have suggestions for that...

The way you've done it looks good.

> Also I noticed this repetition:

Yep definitely an error.

2020-12-14 18:08 UTC, BreakSecurity commented
Let me know. I have never worked with laravel so I read briefly about validation rules and the `sometimes` use cases.

I would like to make telephone number `required `too do you agree?

2020-12-14 23:00 UTC, sampoyigi requested changes
The telephone field used to be `required` but had a lot of forum posts requesting to remove the `required` rule. Maybe in future versions, we'll have a way to extend/override validation rules

2020-12-14 23:00 UTC, sampoyigi commented on components/Checkout.php
> +            $namedRules[] = ['address.state', 'lang:igniter.cart::default.checkout.label_state', 'sometimes|max:128'];
We don't need `sometimes` rule on the address_1 field since its always available... Can you add the missing validation rule for address_2 field?

2020-12-16 12:26 UTC, BreakSecurity commented
Done let me know how can I implement overriding of val rule ;)

2020-12-16 13:55 UTC, sampoyigi commented
I'm still thinking of how to go about `overriding validation rules`, hopefully, I can come up with something before the next update 🙏

2020-12-16 13:56 UTC, merged

2020-12-16 13:57 UTC, sampoyigi commented
Thank you and Happy first TastyIgniter PR 😉 !