Fix quantity count when validating menu option
tastyigniter/ti-ext-cart pull request #36
Opened 2020-12-14 20:20 UTC by jsongerber

When the quantity option type is used with a min or max quantity defined, the validating wasn't working.
The count was always the count of the options, because the quantity option returns a multidimensional array, where other option types return an array of selected values.
(I may submit more pull requests in the future as I'm starting to use your system, please tell me if you'd like that I open an issue first next time, or if you have some coding standard you'd like I use)

2020-12-15 06:57 UTC, ryanmitchell commented
Asides from the styleCI issue which you need to fix (https://github.styleci.io/analyses/e7BPjr?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) this looks good to me.

Good catch and fix.

2020-12-15 06:57 UTC, ryanmitchell approved these changes

2020-12-15 14:00 UTC, jsongerber commented
Done

2020-12-15 14:04 UTC, ryanmitchell commented
@sampoyigi im happy for this merge. 

Thanks @jsongerber !

2020-12-15 23:24 UTC, sampoyigi requested changes

2020-12-15 23:24 UTC, sampoyigi commented on classes/CartManager.php
> +        if ('quantity' == $menuOption->getDisplayTypeAttribute()) {
Should be $menuOption->display_type 😉

2020-12-16 07:58 UTC, jsongerber commented on classes/CartManager.php
> +        if ('quantity' == $menuOption->getDisplayTypeAttribute()) {
Sure, done

2020-12-16 19:30 UTC, sampoyigi approved these changes

2020-12-16 19:32 UTC, merged

2020-12-16 19:32 UTC, sampoyigi commented
@jsongerber Welcome onboard! Thank you 👍

2020-12-16 20:37 UTC, jsongerber commented
@sampoyigi Thanks! Glad to be using your cool platform 😀