Takeover of @GrantBartlett commit - Part 2
tastyigniter/ti-ext-cart pull request #49
Opened 2021-02-15 21:01 UTC by BreakSecurity

Related to https://github.com/tastyigniter/ti-theme-orange/pull/26

and

https://github.com/tastyigniter/ti-theme-orange/pull/22

2021-02-17 23:33 UTC, sampoyigi requested changes
Thank you for picking this up!

2021-02-17 23:33 UTC, sampoyigi commented on components/cartbox/mobile.blade.php
> +    class="{{ !$pageIsCheckout ? 'fixed-bottom' : 'mt-3' }}{{ $pageIsCart ? 'hide' : ' d-block d-lg-none' }}"
This should be `d-md-none`

2021-02-17 23:33 UTC, sampoyigi commented on components/cartbox/container.blade.php
> +<div class="{{ $pageIsCheckout ? 'd-block' : 'affix-cart d-lg-block' }}">
Should be `{{ $pageIsCart ?: 'affix-cart d-none d-md-block' }}`

2021-02-19 20:44 UTC, BreakSecurity commented
Done @sampoyigi

2021-02-19 20:52 UTC, BreakSecurity commented on components/cartbox/mobile.blade.php
>      @if ($pageIsCheckout)
Should we get rid of this empty if?

2021-02-22 11:34 UTC, sampoyigi commented on components/cartbox/mobile.blade.php
>      @if ($pageIsCheckout)
Which one?

2021-02-22 23:29 UTC, sampoyigi commented
Thank you @BreakSecurity! @GrantBartlett's approach with `lg` looks cleaner.

2021-02-22 23:46 UTC, sampoyigi approved these changes

2021-02-22 23:46 UTC, merged